Repository metwork-framework/mfdata, pull requests merged in 2018-12, with the labels that each got.

#26 fix: don't start plugins during installation or uninstallation
  adm/conf_monitor.sh
Labels: Status: Closed

#31 fix: fix missing configuration for no_match policy in switch plugin
  plugins/switch/config.ini
  plugins/switch/main.py
Labels: Status: Review Needed

#32 fix: fix issues with xattrfile move_or_copy/hardlink_or_copy
  layers/layer1_python3/0200_xattrfile/tests/test_basic.py
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
Labels: Merge Now, Status: Pending

#33 fix: fix magic identification at plugin level override
  plugins/switch/main.py
Labels: Merge Now, Status: Pending

#37 [WIP] refactor: use new plugin_wrapper
  adm/_make_circus_conf
Labels: Merge Now, Status: Review Needed

#38 add parameter extract_tags to method AcquisitionStep.get_stats_client
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Status: Review Needed

#39 feat: add parameter extract_tags to method AcquisitionStep.get_stats_client
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Merge Now, Status: Review Needed
