Repository metwork-framework/mfdata, pull requests merged in 2019-05, with the labels that each got.

#131 fix: fix building issues with proxy
  bootstrap.sh
  doc/mfdata_load_env.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
  layers/layer1_python3/layer_custom.md
Labels: Status: Review Needed

#132 fix: fix issue 'bad magic file in a plugin can break the switch plugin'
  plugins/switch/main.py
Labels: Status: Closed

#134 docs: fix typo
  doc/conf.py
  doc/mfdata_load_env.md
Labels: Merge Now, Status: Revision Needed

#133 build: shell to generate X files of size N in one second
  adm/Makefile
  adm/generate_random_files.py
Labels: Status: Review Needed

#136 docs: Update MFDATA documentation
  doc/Makefile
  doc/mfdata_miscellaneous.md
  doc/mfdata_tuning_monitoring.md
Labels: Merge Now, Status: Review Needed

#137 build: remove layer python
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
  layers/layer9_python/layer_custom.md
Labels: Merge Now, Status: Review Needed

#138 cleanly stop the extra daemon
  adm/mfxxx.stop.custom
Labels: Status: Review Needed

#139 docs: fix invalid generated images link url
  doc/_images/archive_image_flow.jpg
  doc/_images/ftpsend_to_mybox.jpg
  doc/_images/grafana_create_dashboard1.jpg
  doc/_images/grafana_create_dashboard2.jpg
  doc/_images/grafana_create_dashboard3.jpg
  doc/_images/grafana_edit_axes_dashboard1.jpg
  doc/_images/grafana_edit_axes_dashboard2.jpg
  doc/_images/grafana_edit_display_dashboard1.jpg
  doc/_images/grafana_edit_display_dashboard2.jpg
  doc/_images/grafana_edit_general_dashboard1.jpg
  doc/_images/grafana_edit_general_dashboard2.jpg
  doc/_images/grafana_edit_legend_dashboard1.jpg
  doc/_images/grafana_edit_metrics_dashboard1.jpg
  doc/_images/grafana_edit_metrics_dashboard2.jpg
  doc/_images/grafana_home.jpg
  doc/_images/grafana_login.jpg
  doc/_images/grafana_mfdata_dashboard.jpg
  doc/_images/grafana_new_graph_dashboard.jpg
  doc/_images/grafana_quick_ranges_dashboard.jpg
  doc/_images/grafana_refresh_dashboard.jpg
  doc/_images/grafana_save_dashboard.jpg
  doc/_images/grafana_view_metrics_dashboard.jpg
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/_images/move_image_flow.jpg
  doc/_images/overall_architecture.jpg
  doc/_images/png_to_jpeg_flow.jpg
  doc/conf.py
  doc/mfdata_additional_tutorials.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
  doc/mfdata_tuning_monitoring.md
Labels: Status: Review Needed

#140 add optional mqtt 3.1.1 incoming messages support
  .gitignore
  config/config.ini
  plugins/Makefile
  plugins/mqtt_listener/.layerapi2_dependencies
  plugins/mqtt_listener/.layerapi2_label
  plugins/mqtt_listener/Makefile
  plugins/mqtt_listener/bin/extra_daemon_mqtt_listener.py
  plugins/mqtt_listener/config.ini
  plugins/mqtt_listener/python3_virtualenv_sources/requirements-to-freeze.txt
  plugins/mqtt_listener/python3_virtualenv_sources/requirements3.txt
Labels: Status: Review Needed

#141 build: gitignore fix
  .gitignore
Labels: Merge Now

#143 Update mfdata_tuning_monitoring.md
  doc/mfdata_tuning_monitoring.md
Labels: Merge Now, Status: Review Needed

#145 feat: use envtpl new option --reduce-multi-blank-lines
  adm/_make_circus_conf
  adm/_make_directory_observer_conf
  adm/_make_nginx_conf
  adm/_make_switch_conf
  doc/Makefile
  layers/layer1_python3/0300_acquisition/acquisition/configargparse_confparser.py
Labels: Status: Review Needed
