Repository metwork-framework/mfdata, pull requests merged in 2019-04, with the labels that each got.

#106 refactor: drop duplicate name (the name is already given in CLI)
  adm/templates/plugins/archive/cookiecutter.json
  adm/templates/plugins/default/cookiecutter.json
  adm/templates/plugins/delete/cookiecutter.json
  adm/templates/plugins/fork/cookiecutter.json
  adm/templates/plugins/ftpsend/cookiecutter.json
  adm/templates/plugins/move/cookiecutter.json
Labels: Status: Review Needed, backport-to-0.5, backport-to-0.6

#109 docs: Update MFDATA documentation + add "Edit on GitHub"
  .metwork-framework/plugins_guide.md
  doc/Makefile
  doc/_templates/breadcrumbs.html
  doc/api_xattrfile.rst
  doc/conf.py
  doc/mfdata_additional_tutorials.md
  doc/mfdata_create_plugins.md
  doc/mfdata_deploy_plugin.md
  doc/mfdata_miscellaneous.md
  layers/layer1_python3/0200_xattrfile/xattrfile/get_tag.py
  layers/layer1_python3/0200_xattrfile/xattrfile/print_tags.py
  layers/layer1_python3/0200_xattrfile/xattrfile/set_tag.py
Labels: Status: Review Needed

#82 refactor: use std_redirect inside of custom circus_stream_multifiles
  adm/_make_circus_conf
  layers/layer1_python3/0500_circus_streammultifiles/Makefile
  layers/layer1_python3/0500_circus_streammultifiles/Makefile.mk
  layers/layer1_python3/0500_circus_streammultifiles/circus_streammultifiles/__init__.py
  layers/layer1_python3/0500_circus_streammultifiles/setup.py
Labels: Status: Review Needed

#110 feat: introduce log management with mfadmin
  config/circus.ini.custom
  config/config.ini
  config/nginx.conf
Labels: Status: Review Needed

#112 chore: remove dead code
  layers/layer1_python3/0100_directory_observer/directory_observer/directory_observer.py
Labels: Status: Review Needed

#111 docs: Update MFDATA documentation
  doc/_static/empty
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/conf.py
  doc/images/grafana_home.jpg
  doc/images/grafana_login.jpg
  doc/images/grafana_mfdata_dashboard.jpg
  doc/images/overall_architecture.jpg
  doc/index.rst
  doc/mfdata_additional_tutorials.md
  doc/mfdata_and_magic.md
  doc/mfdata_create_plugins.md
  doc/mfdata_debug_plugin.md
  doc/mfdata_deploy_plugin.md
  doc/mfdata_intro.md
  doc/mfdata_load_env.md
  doc/mfdata_log.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
  doc/mfdata_tuning_monitoring.md
  doc/src/overall_architecture.graphml
  doc/todo.rst
Labels: Status: Review Needed

#113 docs: Update MFDATA documentation
  doc/images/grafana_create_dashboard1.jpg
  doc/images/grafana_create_dashboard2.jpg
  doc/images/grafana_create_dashboard3.jpg
  doc/images/grafana_edit_axes_dashboard1.jpg
  doc/images/grafana_edit_axes_dashboard2.jpg
  doc/images/grafana_edit_display_dashboard1.jpg
  doc/images/grafana_edit_display_dashboard2.jpg
  doc/images/grafana_edit_general_dashboard1.jpg
  doc/images/grafana_edit_general_dashboard2.jpg
  doc/images/grafana_edit_legend_dashboard1.jpg
  doc/images/grafana_edit_metrics_dashboard1.jpg
  doc/images/grafana_edit_metrics_dashboard2.jpg
  doc/images/grafana_new_graph_dashboard.jpg
  doc/images/grafana_quick_ranges_dashboard.jpg
  doc/images/grafana_refresh_dashboard.jpg
  doc/images/grafana_save_dashboard.jpg
  doc/images/grafana_view_metrics_dashboard.jpg
  doc/mfdata_additional_tutorials.md
  doc/mfdata_log.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_tuning_monitoring.md
  layers/layer1_python2/documented_utilities
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
  layers/layer1_python3/0300_acquisition/acquisition/archive_step.py
  layers/layer1_python3/0300_acquisition/acquisition/delete_step.py
  layers/layer1_python3/0300_acquisition/acquisition/fork_step.py
  layers/layer1_python3/0300_acquisition/acquisition/move_step.py
  layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py
  layers/layer1_python3/documented_utilities
  layers/layer1_python3/layer_custom.md
Labels: Status: Review Needed

#114 docs: Update MFDATA documentation
  doc/_static/css/override_theme.css
  doc/conf.py
  doc/images/logo-metwork.png
  doc/images/metwork.ico
  layer_custom.md
Labels: Status: Review Needed

#116 port redis_service feature of mfserv to mfdata
  adm/_make_circus_conf
  adm/templates/plugins/archive/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/archive/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/delete/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/delete/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/fork/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/fork/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/move/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
  config/Makefile
  config/redis_plugin_xxx.conf
Labels: Status: Review Needed

#117 docs: Add intersphinx mapping + fix typo
  doc/conf.py
  doc/mfdata_additional_tutorials.md
  doc/mfdata_deploy_plugin.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
  doc/mfdata_tuning_monitoring.md
  layer_custom.md
Labels: Status: Review Needed

#115 Move policy keep tags
  layers/layer1_python3/0300_acquisition/acquisition/archive_step.py
  layers/layer1_python3/0300_acquisition/acquisition/delete_step.py
  layers/layer1_python3/0300_acquisition/acquisition/fork_step.py
  layers/layer1_python3/0300_acquisition/acquisition/move_step.py
  layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py
  layers/layer1_python3/0300_acquisition/acquisition/step.py
  layers/layer1_python3/0300_acquisition/tests/test_delete_step.py
  layers/layer1_python3/0300_acquisition/tests/test_move.py
  layers/layer1_python3/0300_acquisition/tests/test_reinject.py
Labels: Status: Review Needed

#121 feat: port "extra_daemon" feature from mfserv to mfdata
  adm/_make_circus_conf
  adm/templates/plugins/archive/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/delete/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/fork/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
Labels: Status: Review Needed

#122 Changelogs
  .gitignore
  doc/Makefile
  doc/changelogs.rst
  doc/index.rst
Labels: Status: Review Needed

#123 refactor: add failure_policy and failure_policy_move_* attributes in …
  adm/templates/plugins/archive/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/delete/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/fork/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
Labels: Status: Review Needed

#124 docs: fix typo + add missing layers 'custom' documentation
  doc/index.rst
  doc/mfdata_load_env.md
  layer_custom.md
  layers/layer9_default/layer_custom.md
  layers/layer9_python/layer_custom.md
Labels: Status: Review Needed

#127 misc changes around issue 126
  adm/Makefile
  adm/_make_nginx_conf
  config/content_by_lua.lua
Labels: Merge Now, Status: Review Needed

#128 Issue126 real fix
  adm/garbage_collector.sh
Labels: Merge Now, Status: Review Needed, backport-to-0.5, backport-to-0.6
