Repository metwork-framework/mfdata, pull requests merged in 2019-08, with the labels that each got.

#162 build: synutil_lua => mfutil_lua migration
  config/content_by_lua.lua
Labels: Merge Now, Status: Review Needed

#163 build: use conf monitor hooks
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed, backport-to-0.7, backport-to-0.8

#168 docs: Update MFDATA documentation
  doc/_downloads/amqp/amqp_publish.py
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
Labels: Status: Review Needed

#169 fix: fix logging issue with mqtt_listener in some cases
  plugins/mqtt_listener/bin/extra_daemon_mqtt_listener.py
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#171 fix: fix amqp listener plugin configuration
  plugins/amqp_listener/config.ini
Labels: Merge Now, Status: Review Needed

#172 fix: important fix about failure_policy_move_keep_tags
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Merge Now, Status: Review Needed, backport-to-0.7, backport-to-0.8
