Repository metwork-framework/mfdata, pull requests merged in 2019-10, with the labels that each got.

#188 Misc
  adm/Makefile
  adm/_check_circus_conf
  adm/_make_circus_conf
  adm/mfxxx.start.custom
  adm/mfxxx.status.custom
  config/config.ini
  plugins/switch/config.ini
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed

#189 feat: build mfdata without mfcom (mfcom layers are now included in mf…
  .gitignore
  .layerapi2_dependencies
  adm/Makefile
  adm/templates/plugins/_common/Makefile
  config/Makefile
  config/nginx.conf
  doc/mfdata_deploy_plugin.md
  doc/mfdata_quick_start.md
  layer_custom.md
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer9_default/.layerapi2_dependencies
  plugins/amqp_listener/Makefile
  plugins/debug/Makefile
  plugins/mqtt_listener/Makefile
  plugins/switch/Makefile
  plugins/unbzip2/Makefile
  plugins/ungzip/Makefile
Labels: Merge Now, Status: Review Needed

#190 feat: refactor around #154 issue
  adm/_make_circus_conf
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/listener/cookiecutter.json
  adm/templates/plugins/listener/hooks
  adm/templates/plugins/listener/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/listener/{{cookiecutter.name}}/.layerapi2_label
  adm/templates/plugins/listener/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/listener/{{cookiecutter.name}}/bin/listener.py
  adm/templates/plugins/listener/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/listener/{{cookiecutter.name}}/crontab
  adm/templates/plugins/listener/{{cookiecutter.name}}/{{cookiecutter.python_version}}_virtualenv_sources/requirements-to-freeze.txt
  config/circus.ini.custom
  config/config.ini
  doc/api_acquisition.rst
  doc/api_xattrfile.rst
  layers/layer1_python3/0300_acquisition/acquisition/__init__.py
  layers/layer1_python3/0300_acquisition/acquisition/base.py
  layers/layer1_python3/0300_acquisition/acquisition/batch_step.py
  layers/layer1_python3/0300_acquisition/acquisition/listener.py
  layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py
  layers/layer1_python3/0300_acquisition/acquisition/step.py
  layers/layer1_python3/0300_acquisition/acquisition/utils.py
  layers/layer1_python3/0300_acquisition/tests/test_basic.py
  plugins/amqp_listener/bin/extra_daemon_amqp_consumer.py
  plugins/amqp_listener/bin/extra_daemon_amqp_consumer_fanout.py
  plugins/amqp_listener/bin/extra_daemon_amqp_consumer_topic.py
  plugins/amqp_listener/config.ini
  plugins/amqp_listener/lib/extra_daemon_amqp_listener.py
  plugins/mqtt_listener/bin/extra_daemon_mqtt_listener.py
Labels: Merge Now, Status: Review Needed

#191 feat: allow "-" and "." in http receiver
  config/content_by_lua.lua
Labels: Merge Now, Status: Review Needed, backport-to-0.8, backport-to-0.9

#195 feat: introduce acquisition decorators for gunzip and bunzip2
  doc/api_acquisition.rst
  layers/layer1_python3/0300_acquisition/acquisition/batch_step.py
  layers/layer1_python3/0300_acquisition/acquisition/decorators.py
  layers/layer1_python3/0300_acquisition/tests/test_decorators.py
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#197 feat: change the behavior of hardlinks methods to provide atomicity
  layers/layer1_python3/0200_xattrfile/tests/test_basic.py
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed, backport-to-0.8, backport-to-0.9

#201 Issue198
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
  layers/layer1_python3/0300_acquisition/acquisition/base.py
  layers/layer1_python3/0300_acquisition/acquisition/move_step.py
  layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py
  layers/layer1_python3/0300_acquisition/acquisition/step.py
  layers/layer1_python3/0300_acquisition/acquisition/uncompress_step.py
  plugins/amqp_listener/lib/extra_daemon_amqp_listener.py
  plugins/mqtt_listener/bin/extra_daemon_mqtt_listener.py
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#202 feat: change the behavior of hardlinks methods to provide atomicity
  layers/layer1_python3/0200_xattrfile/tests/test_basic.py
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed

#204 Issue198fix
  plugins/switch/main.py
Labels: Merge Now, Status: Revision Needed, backport-to-0.9

#207 fix: fix failure_policy_move_keep_tags configuration key
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Merge Now, Priority: Critical, Status: Review Needed, backport-to-0.9
