Repository metwork-framework/mfdata, pull requests merged in 2019-01, with the labels that each got.

#41 [WIP] build: change for new mfcom autorestart plugin
  config/circus.ini.custom
Labels: Merge Now, Status: Pending, Status: Review Needed

#44 feat: provide a default value for summary key during plugins bootstrap
  adm/templates/plugins/archive/cookiecutter.json
  adm/templates/plugins/default/cookiecutter.json
  adm/templates/plugins/delete/cookiecutter.json
  adm/templates/plugins/fork/cookiecutter.json
  adm/templates/plugins/ftpsend/cookiecutter.json
  adm/templates/plugins/move/cookiecutter.json
Labels: Status: Review Needed

#45 [WIP] feat: Changes in management of layer dependencies and metapackage names
  .drone.yml
  .layerapi2_dependencies
  Makefile
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_default/.layerapi2_label
  layers/layer9_default/Makefile
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
Labels: Merge Now, Status: Pending

#46 [WIP] feat: execute integration tests directly from mfdata module
  .drone.yml
  integration_tests/0001_test_mfdata_operational/test_mfdata_operational.sh
  run_integration_tests.sh
Labels: Status: Review Needed
