Repository metwork-framework/mfdata, pull requests merged in 2019-06, with the labels that each got.

#144 docs: generate automatically changelogs entries in changelogs.rst file
  .gitignore
  doc/Makefile
  doc/changelogs.tmpl
Labels: Merge Now, Status: Review Needed

#146 docs: Update MFDATA documentation
  doc/_images/overall_architecture.jpg
  doc/mfdata_miscellaneous.md
  doc/src/overall_architecture.graphml
Labels: Merge Now, Status: Review Needed

#142 feat: use template inheritance for mfdata plugins (inspired by mfserv)
  adm/templates/plugins/_common/Makefile
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/_common/crontab
  adm/templates/plugins/_common/hooks/post_gen_project.py
  adm/templates/plugins/_common/main.py
  adm/templates/plugins/_common/{{cookiecutter.python_version}}_virtualenv_sources/requirements-to-freeze.txt
  adm/templates/plugins/archive/hooks
  adm/templates/plugins/archive/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/archive/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/archive/{{cookiecutter.name}}/main.py
  adm/templates/plugins/default/cookiecutter.json
  adm/templates/plugins/default/hooks
  adm/templates/plugins/default/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/crontab
  adm/templates/plugins/default/{{cookiecutter.name}}/main.py
  adm/templates/plugins/default/{{cookiecutter.name}}/{{cookiecutter.python_version}}_virtualenv_sources/requirements-to-freeze.txt
  adm/templates/plugins/delete/hooks
  adm/templates/plugins/delete/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/delete/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/delete/{{cookiecutter.name}}/main.py
  adm/templates/plugins/fork/hooks
  adm/templates/plugins/fork/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/fork/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/fork/{{cookiecutter.name}}/main.py
  adm/templates/plugins/ftpsend/hooks
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/move/hooks
  adm/templates/plugins/move/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/move/{{cookiecutter.name}}/main.py
  integration_tests/0001_python3_plugin/test.sh
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
  integration_tests/0003_delete_plugin/stdin
  integration_tests/0003_delete_plugin/test.sh
  integration_tests/0004_move_plugin/stdin
  integration_tests/0004_move_plugin/test.sh
  integration_tests/0005_fork_template/stdin
  integration_tests/0005_fork_template/test.sh
  integration_tests/0006_process_a_thousand_files/test.sh
Labels: Status: Review Needed

#150 docs: Update MFDATA documentation
  .gitignore
  doc/_images/grafana_home.jpg
  doc/_images/grafana_login.jpg
  doc/_images/grafana_mfdata_dashboard.jpg
  doc/_images/overall_architecture.jpg
  doc/_images/overall_architecture.svg
  doc/index.rst
  doc/mfdata_how_it_works.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_tuning_monitoring.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#149 fix: create a missing directory during hot reload after a new plugin install
  adm/mfdata_conf_monitor.py
Labels: Status: Review Needed, backport-to-0.6, backport-to-0.7

#155 docs: Update MFDATA documentation
  doc/mfdata_how_it_works.md
  doc/mfdata_log.md
  doc/mfdata_tuning_monitoring.md
Labels: Status: Review Needed

#156 docs: fix typo
  doc/mfdata_and_magic.md
  doc/mfdata_debug_plugin.md
  doc/mfdata_how_it_works.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
Labels: Status: Review Needed

#157 Experimental
  bootstrap.sh
Labels: Merge Now, Status: Review Needed
