Repository metwork-framework/mfdata, pull requests merged in 2019-03, with the labels that each got.

#62 Issue61
  layers/layer1_python3/0200_xattrfile/Makefile.mk
  layers/layer1_python3/0200_xattrfile/tests/test_basic.py
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
  layers/layer1_python3/0300_acquisition/Makefile.mk
Labels: Merge Now, Status: Review Needed, backport-to-0.5

#66 feat: fix #65 and introduce new configuration options around
  config/config.ini
  plugins/switch/config.ini
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed

#64 fix: dump tags on errors (when in debug mode)
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Merge Now, Status: Revision Needed

#68 fix: fix move_or_copy feature when src and dst are not on the same FS
  layers/layer1_python3/0200_xattrfile/tests/test_basic.py
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
Labels: Status: Review Needed

#70 fix: fix intermittent fails of mfdata integration tests
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
Labels: Status: Review Needed

#73 Better move step
  adm/templates/plugins/move/cookiecutter.json
  adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
  layers/layer1_python3/0300_acquisition/acquisition/move_step.py
  layers/layer1_python3/0300_acquisition/tests/test_basic.py
Labels: Status: Review Needed, backport-to-0.5

#74 build: drop old and useless directory
  website_md/metwork_presentation.md
  website_md/mfdata/documentation.md
  website_md/mfdata/short_desc.md
  website_md/mfdata/tuto.md
  website_md/wip/wip.md
Labels: Status: Review Needed

#71 feat: remove circus_autostart and autostart plugins in circus config
  adm/_make_circus_conf
  adm/mfxxx.stop.custom
  config/circus.ini.custom
  config/telegraf.conf.custom
  layers/layer1_python3/0400_circus_autostart/Makefile
  layers/layer1_python3/0400_circus_autostart/Makefile.mk
  layers/layer1_python3/0400_circus_autostart/circus_autostart/__init__.py
  layers/layer1_python3/0400_circus_autostart/setup.py
Labels: Status: Review Needed

#72 fix: fix an integration test
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
Labels: Merge Now, Status: Review Needed

#76 Test 1000 files
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
  integration_tests/0003_process_a_thousand_files/test.sh
  integration_tests/data/Example.png
  integration_tests/data/Example.png.gz
  run_integration_tests.sh
Labels: Merge Now, Status: Review Needed

#77 Add / update MFDATA doc
  .metwork-framework/plugins_guide.md
  doc/Makefile
  doc/conf.py
  doc/images/archive_image_flow.jpg
  doc/images/ftpsend_to_mybox.jpg
  doc/images/move_image_flow.jpg
  doc/images/png_to_jpeg_flow.jpg
  doc/index.rst
  doc/mfdata_additional_tutorials.md
  doc/mfdata_and_magic.md
  doc/mfdata_deploy_plugin.md
  doc/mfdata_intro.md
  doc/mfdata_log.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
  doc/src/archive_image_flow.graphml
  doc/src/ftpsend_to_mybox.graphml
  doc/src/move_image_flow.graphml
  doc/src/png_to_jpeg_flow.graphml
Labels: Status: Review Needed

#81 docs: update MFDATA tutorials
  doc/_downloads/AROME_201811280600.grib2
  doc/_downloads/convert_grib2/main.py
  doc/mfdata_additional_tutorials.md
Labels: Status: Review Needed

#83 docs: we prefer to keep a specific list of what we copy to doc
  doc/Makefile
Labels: Merge Now, Status: Review Needed

#89 build: fix doc makefile
  doc/Makefile
Labels: Merge Now

#90 build: don't hide null files
  .gitignore
Labels: Status: Review Needed

#91 refactor: drop name key in plugins config.ini
  adm/templates/plugins/archive/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/delete/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/fork/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/move/{{cookiecutter.name}}/config.ini
Labels: Merge Now, Status: Review Needed

#95 fix: add garbage_collector.sh call in crontab
  config/crontab.custom
Labels: Status: Review Needed, backport-to-0.5

#99 chore: sync common files from resources repository
  .drone.yml
Labels: Merge Now, Status: Review Needed

#102 docs: Update MFDATA documentation
  .metwork-framework/plugins_guide.md
  doc/_downloads/AROME_201811280600.grib2
  doc/api_acquisition.rst
  doc/api_xattrfile.rst
  doc/conf.py
  doc/index.rst
  doc/mfdata_additional_tutorials.md
  doc/mfdata_create_plugins.md
  doc/mfdata_debug_plugin.md
  doc/mfdata_deploy_plugin.md
  doc/mfdata_miscellaneous.md
  doc/mfdata_quick_start.md
Labels: Status: Review Needed

#103 fix: catch some magic exception with some exotic files
  plugins/switch/main.py
Labels: Status: Review Needed, backport-to-0.5, backport-to-0.6
