Repository metwork-framework/mfdata, pull requests merged in 2019-11, with the labels that each got.

#210 fix: fix get_original_basename/dirname behaviour in debug mode
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Status: Review Needed, backport-to-0.9

#213 feat: allow ,;: in directorie/filenames
  config/content_by_lua.lua
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#215 feat: adaptation to removal of layer misc@mfext
  .layerapi2_dependencies
  adm/Makefile
  adm/templates/plugins/_common/Makefile
  bootstrap.sh
  config/Makefile
  plugins/amqp_listener/Makefile
  plugins/debug/Makefile
  plugins/mqtt_listener/Makefile
  plugins/switch/Makefile
  plugins/unbzip2/Makefile
  plugins/ungzip/Makefile
Labels: Status: Revision Needed

#217 Exception already caught
  plugins/amqp_listener/lib/extra_daemon_amqp_listener.py
Labels: Status: Review Needed

#216 feat: adaptation to removal of layer misc@mfext
  .layerapi2_dependencies
  adm/Makefile
  adm/templates/plugins/_common/Makefile
  bootstrap.sh
  config/Makefile
  plugins/amqp_listener/Makefile
  plugins/debug/Makefile
  plugins/mqtt_listener/Makefile
  plugins/switch/Makefile
  plugins/unbzip2/Makefile
  plugins/ungzip/Makefile
Labels: Merge Now, Status: Review Needed
