Repository metwork-framework/mfdata, pull requests merged in 2019-02, with the labels that each got.

#47 refactor: fix tests about new mflog library
  layers/layer1_python3/0300_acquisition/acquisition/step.py
  layers/layer1_python3/0300_acquisition/tests/test_basic.py
  layers/layer1_python3/0300_acquisition/tests/test_delete_step.py
  layers/layer1_python3/0300_acquisition/tests/test_reinject.py
Labels: Merge Now, Status: Review Needed

#48 refactor: changes for the new mflog lib
  config/Makefile
  config/config.ini
  config/mflog_override.conf
Labels: Merge Now, Status: Revision Needed

#50 Feat: add integration test with png.gz data (test plugins switch, ung…
  integration_tests/0001_python3_plugin/test.sh
  integration_tests/0002_switch_ungzip_archive_plugins/Example.png
  integration_tests/0002_switch_ungzip_archive_plugins/Example.png.gz
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
Labels: Merge Now, Status: Review Needed

#51 Feat: add integration test with png.gz data (test plugins switch, ung…
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
Labels: Merge Now, Status: Review Needed

#52 Feat: add integration test with png.gz data (test plugins switch, ung…
  integration_tests/0002_switch_ungzip_archive_plugins/test.sh
Labels: Merge Now, Status: Review Needed

#57 fix: Fix loss of files between plugin switch and plugin ungzip or other
  layers/layer1_python3/0200_xattrfile/tests/test_basic.py
  layers/layer1_python3/0200_xattrfile/xattrfile/__init__.py
Labels: Merge Now, Status: Review Needed, backport-to-0.4, backport-to-0.5

#60 fix: fix exception function errors when the parameter is an exception…
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Merge Now, Status: Review Needed
