Repository metwork-framework/mfdata, pull requests merged in 2020-05, with the labels that each got.

#276 Suppress mfcom ref
  adm/redis_metwork.py
  adm/templates/plugins/_common/config.ini
  config/config.ini.custom
  layers/layer1_python3/0300_acquisition/acquisition/stats.py
Labels: Status: Revision Needed

#281 build: mfdata build fix
  plugins/httpsend/config.ini
  plugins/switch/config.ini
  plugins/unbzip2/config.ini
  plugins/ungzip/config.ini
Labels: Merge Now, Status: Revision Needed

#282 build: fix variable name
  config/config.ini.custom
Labels: Status: Review Needed

#268 [WIP] mfextaddon_python2
  layers/layer1_python2/.bypass_build_if_missing
Labels: Merge Now, Status: Review Needed

#284 build: don't run python2 test if python2@mfext is not installed
  integration_tests/0001_python2_plugin/test.sh
Labels: Merge Now, Status: Review Needed

#285 build: remove some generated files
  plugins/httpsend/.layerapi2_label
  plugins/httpsend/.release_ignore
  plugins/switch/.layerapi2_label
  plugins/unbzip2/.layerapi2_label
  plugins/ungzip/.layerapi2_label
Labels: Merge Now

#286 build: build fix because of mfutil changes
  adm/plugins.py
  layers/layer1_python3/0300_acquisition/acquisition/base.py
  layers/layer1_python3/0300_acquisition/acquisition/utils.py
Labels: Status: Review Needed

#287 feat: allow binary packages with pip by default for plugins
  adm/templates/plugins/_common/python2_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/_common/python3_virtualenv_sources/allow_binary_packages
Labels: Merge Now, Status: Review Needed

#289 build: mfdata fixes
  adm/templates/plugins/_common/main.py
  layers/layer1_python3/0300_acquisition/acquisition/copy_step.py
Labels: Merge Now

#291 fix: typo in .releaseignore file
  adm/templates/plugins/_common/.releaseignore
  adm/templates/plugins/python2/{{cookiecutter.name}}/.release_ignore
  adm/templates/plugins/python2/{{cookiecutter.name}}/.releaseignore
  adm/templates/plugins/python3/{{cookiecutter.name}}/.release_ignore
  adm/templates/plugins/python3/{{cookiecutter.name}}/.releaseignore
  plugins/amqplistener/.gitignore
  plugins/archive/.gitignore
  plugins/common.mk
  plugins/copy/.gitignore
  plugins/delete/.gitignore
  plugins/fork/.gitignore
  plugins/ftpsend/.gitignore
  plugins/guess_file_type/.gitignore
  plugins/httpsend/.gitignore
  plugins/move/.gitignore
  plugins/mqttlistener/.gitignore
  plugins/switch/.gitignore
  plugins/unbzip2/.gitignore
  plugins/ungzip/.gitignore
Labels: Status: Review Needed, backport-to-1.0
