Repository metwork-framework/mfdata, pull requests merged in 2020-10, with the labels that each got.

#336 fix: remove old parameters about AMQP/MQTT from the module configuration file
  config/config.ini.custom
Labels: Status: In Progress, backport-to-1.0

#338 fix: self._consumer.on_message is not set after exception
  plugins/amqplistener/bin/amqp_listener.py
Labels: Status: Review Needed, backport-to-1.0

#342 build: add .configuration_cache in plugins default .gitignore
  adm/templates/plugins/_common/.gitignore
Labels: Status: Review Needed, backport-to-1.0

#345 feat: add some new config options to amqp_listener plugin (see issue #317)
  plugins/amqplistener/bin/amqp_listener.py
  plugins/amqplistener/config.ini.custom
Labels: Status: Review Needed
