Repository metwork-framework/mfdata, pull requests merged in 2020-03, with the labels that each got.

#259 [WIP] fix: fix typo in configuration key for amqp (topic mode)
  config/config.ini.custom
Labels: Merge Now, Status: Review Needed

#261 [WIP] fix: fix bug in amqp topic mode
  plugins/amqp_listener/lib/extra_daemon_amqp_listener.py
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#258 [WIP] fix: fix typo in configuration key for amqp (topic mode)
  config/config.ini
Labels: Merge Now, Status: Review Needed

#263 feat: add a keep_original_basename in copy/move_to_plugin_step
  layers/layer1_python3/0300_acquisition/acquisition/step.py
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#265 fix: fix syslog nginx conf
  config/nginx.conf
Labels: Merge Now, Status: Review Needed

#266 build: better crontab documentation
  adm/templates/plugins/_common/crontab
Labels: Status: Review Needed

#269 feat: The number of processes of the switch plugin is now configurabl…
  config/config.ini.custom
  plugins/switch/config.ini
Labels: Status: Review Needed, backport-to-0.9

#270 feat: add strftime placeholders for httpsend plugin
  adm/templates/plugins/httpsend/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/httpsend/{{cookiecutter.name}}/send.py
Labels: Status: Review Needed
