Repository metwork-framework/mfdata, pull requests merged in 2020-02, with the labels that each got.

#237 build: pythonX_misc layer drop
  layer_custom.md
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
Labels: Merge Now, Status: Revision Needed

#238 build: pythonX_misc layer drop
  layers/layer1_python2/.layerapi2_dependencies
Labels: Merge Now, Status: Revision Needed

#239 Drop python x misc
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
Labels: Status: Review Needed

#243 feat: use safe_eval from mfutil to evaluate conditions in switch plugin
  plugins/switch/main.py
Labels: Status: Review Needed

#246 Revert "feat: use safe_eval from mfutil to evaluate conditions in swi…
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed

#247 feat: remove absolute log paths from log_proxy usages (LOGPROXY_LOG_D…
  adm/templates/plugins/_common/crontab
  config/circus.ini.custom
  config/crontab.custom
  config/nginx.conf
  doc/mfdata_miscellaneous.md
Labels: Status: Review Needed

#248 feat: allow empty nginx uploads
  config/content_by_lua.lua
Labels: Merge Now, Status: Review Needed

#245 issue242
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed

#255 build: revert new eval behaviour with a feature flag
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed

#256 build: switch to new eval behaviour
  plugins/switch/main.py
Labels: Merge Now, Status: Review Needed
