Repository metwork-framework/mfdata, pull requests merged in 2020-06, with the labels that each got.

#294 feat: add python switch rule
  adm/_make_switch_conf
  layers/layer1_python3/0300_acquisition/acquisition/switch_rules.py
Labels: backport-to-1.0

#296 feat: preparing issue227
  layers/layer1_python3/0300_acquisition/acquisition/base.py
  layers/layer1_python3/0300_acquisition/acquisition/copy_step.py
  layers/layer1_python3/0300_acquisition/acquisition/move_step.py
  layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py
  layers/layer1_python3/0300_acquisition/acquisition/step.py
  layers/layer1_python3/0300_acquisition/acquisition/switch_rules.py
  layers/layer1_python3/0300_acquisition/acquisition/switch_step.py
  layers/layer1_python3/0300_acquisition/acquisition/transform_step.py
  layers/layer1_python3/0300_acquisition/acquisition/utils.py
Labels: Merge Now, backport-to-1.0

#298 Experimental
  adm/_switch.stop
  layers/layer1_python2/.bypass_build_if_missing
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python2/.layerapi2_label
  layers/layer1_python2/0300_acquisition
  layers/layer1_python2/Makefile
  layers/layer1_python2/documented_utilities
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/0300_acquisition/Makefile
  layers/layer1_python3/0300_acquisition/Makefile.mk
  layers/layer1_python3/0300_acquisition/acquisition/__init__.py
  layers/layer1_python3/0300_acquisition/acquisition/archive_step.py
  layers/layer1_python3/0300_acquisition/acquisition/base.py
  layers/layer1_python3/0300_acquisition/acquisition/batch_step.py
  layers/layer1_python3/0300_acquisition/acquisition/copy_step.py
  layers/layer1_python3/0300_acquisition/acquisition/decorators.py
  layers/layer1_python3/0300_acquisition/acquisition/delete_step.py
  layers/layer1_python3/0300_acquisition/acquisition/fork_step.py
  layers/layer1_python3/0300_acquisition/acquisition/inject_file.py
  layers/layer1_python3/0300_acquisition/acquisition/listener.py
  layers/layer1_python3/0300_acquisition/acquisition/move_step.py
  layers/layer1_python3/0300_acquisition/acquisition/reinject_step.py
  layers/layer1_python3/0300_acquisition/acquisition/stats.py
  layers/layer1_python3/0300_acquisition/acquisition/step.py
  layers/layer1_python3/0300_acquisition/acquisition/switch_rules.py
  layers/layer1_python3/0300_acquisition/acquisition/switch_step.py
  layers/layer1_python3/0300_acquisition/acquisition/transform_step.py
  layers/layer1_python3/0300_acquisition/acquisition/unbzip2_step.py
  layers/layer1_python3/0300_acquisition/acquisition/uncompress_step.py
  layers/layer1_python3/0300_acquisition/acquisition/ungzip_step.py
  layers/layer1_python3/0300_acquisition/acquisition/utils.py
  layers/layer1_python3/0300_acquisition/setup.py
  layers/layer1_python3/0300_acquisition/tests/__init__.py
  layers/layer1_python3/0300_acquisition/tests/test.ini
  layers/layer1_python3/0300_acquisition/tests/test_archive.py
  layers/layer1_python3/0300_acquisition/tests/test_basic.py
  layers/layer1_python3/0300_acquisition/tests/test_batch.py
  layers/layer1_python3/0300_acquisition/tests/test_decorators.py
  layers/layer1_python3/0300_acquisition/tests/test_delete_step.py
  layers/layer1_python3/0300_acquisition/tests/test_fork.py
  layers/layer1_python3/0300_acquisition/tests/test_move.py
  layers/layer1_python3/0300_acquisition/tests/test_reinject.py
  layers/layer1_python3/0300_acquisition/tests/test_utils.py
Labels: Merge Now
