Repository metwork-framework/mfdata, pull requests merged in 2020-01, with the labels that each got.

#220 build: some fixes about recent log refactoring
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed

#221 build: fix crontabs
  adm/templates/plugins/_common/crontab
  adm/templates/plugins/archive/{{cookiecutter.name}}/crontab
  config/crontab.custom
Labels: Merge Now

#223 build: configparser_extended drop
  adm/_make_circus_conf
  adm/_make_directory_observer_conf
  adm/_make_switch_conf
  adm/before_start_directory_observer
  layers/layer1_python3/0100_directory_observer/directory_observer/directory_observer.py
  layers/layer1_python3/0100_directory_observer/requirements.txt
  plugins/switch/main.py
Labels: Merge Now, Status: Revision Needed

#224 build: opinionated_configparser changes
  adm/_make_circus_conf
  adm/_make_directory_observer_conf
  adm/_make_switch_conf
  adm/before_start_directory_observer
  plugins/switch/main.py
Labels: Merge Now, Status: Revision Needed

#225 build: fix integration tests
  adm/_make_circus_conf
  adm/_make_directory_observer_conf
  adm/_make_switch_conf
  adm/before_start_directory_observer
  config/nginx.conf
  layers/layer1_python3/0300_acquisition/acquisition/configargparse_confparser.py
Labels: Merge Now, Status: Review Needed

#230 feat: improve debug logs for switch plugin
  plugins/switch/main.py
Labels: Status: Review Needed

#231 build: reflecting mfext changes
  adm/mfdata_conf_monitor.py
  config/circus.ini.custom
  plugins/switch/config.ini
Labels: Merge Now, Status: Review Needed

#232 Mfserv issue269
  config/circus.ini.custom
Labels: Status: Review Needed

#235 fix: remove rlimit_core (because of `ulimit -c 0` in mfext)
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/ftpsend/{{cookiecutter.name}}/config.ini
  config/circus.ini.custom
  doc/mfdata_additional_tutorials.md
  doc/mfdata_tuning_monitoring.md
Labels: Status: Review Needed
