Repository metwork-framework/mfdata, pull requests merged in 2021-06, with the labels that each got.

#394 fix: configure step failure policy for reinject steps
  adm/_make_circus_conf
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#399 fix: fix typo in error messsage
  plugins/ftpsend/main.py
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#398 feat: add sftpsend plugin
  plugins/sftpsend/.gitignore
  plugins/sftpsend/.layerapi2_dependencies
  plugins/sftpsend/Makefile
  plugins/sftpsend/config.ini.custom
  plugins/sftpsend/main.py
Labels: Status: Revision Needed, backport-to-1.1

#403 build: missing Makefile change for new sftpsend plugin
  plugins/Makefile
Labels: Status: Review Needed, backport-to-1.1
