Repository metwork-framework/mfdata, pull requests merged in 2022-01, with the labels that each got.

#421 feat: build on centos8
  .build_os
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/integration_tests.sh
Labels: Status: Revision Needed, Status: Merge Now

#424 fix: fix important typo about monitoring feature of mfdata
  config/nginx.conf
Labels: Status: Review Needed, backport-to-1.2

#422 fix: fix the variable used by watched_directories in comment
  config/config.ini.custom
Labels: Status: Review Needed
